In [1]:
import torch

In [2]:
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1347, 0.8078, 0.2011],
        [0.5678, 0.8939, 0.1973],
        [0.8610, 0.1252, 0.3793],
        [0.5878, 0.8210, 0.4821],
        [0.0300, 0.9285, 0.5482]])
